services:
  test-backend-dotnet1:
    build:
      target: development
    image: test-backend-dotnet1-development
    container_name: test-backend-dotnet1-test
    user: root
    entrypoint: sh -c "cd /home/dotnet && chown -R dotnet:dotnet . && su dotnet -c 'dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=./test-output/'"
    volumes:
      - ./Test.Backend.Dotnet1.sln:/home/dotnet/Test.Backend.Dotnet1.sln
      - ./src/Test.Backend.Dotnet1.Core:/home/dotnet/src/Test.Backend.Dotnet1.Core
      - ./test/Test.Backend.Dotnet1.Core.Tests:/home/dotnet/test/Test.Backend.Dotnet1.Core.Tests
      - ./src/Test.Backend.Dotnet1.Api:/home/dotnet/src/Test.Backend.Dotnet1.Api
      - ./test/Test.Backend.Dotnet1.Api.Tests:/home/dotnet/test/Test.Backend.Dotnet1.Api.Tests
      - ./test/Test.Backend.Dotnet1.Api.Tests/test-output:/home/dotnet/test/Test.Backend.Dotnet1.Api.Tests/test-output
      - ./test/Test.Backend.Dotnet1.Core.Tests/test-output:/home/dotnet/test/Test.Backend.Dotnet1.Core.Tests/test-output
